LojaGaucha/Models/ItemVenda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace LojaGaucha.Models
{
    [Table("ItensVenda")]
    public class ItemVenda
    {
        [Key]
        public int ItemVendaId { get; set; }
        public Produto ItemVendaProduto { get; set; }
        public int ProdutoId { get; set; }
        public double ItemVendaPreco { get; set; }
        public int ItemVendaQuantidade { get; set; }
        public string IdCarrinho { get; set; }
        public DateTime DataDaAdicao { get; set; }
    }
}

LojaGaucha/Controllers/ItemVendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LojaGaucha.Models;
using LojaGaucha.DAL;

namespace LojaGaucha.Controllers
{
    public class ItemVendaController : Controller
    {
        private Entities db = new Entities();

        // GET: ItemVenda
        public ActionResult Index()
        {
            var itensVenda = db.ItensVenda.Include(i => i.ItemVendaProduto);
            return View(itensVenda.ToList());
        }
        // GET: ItemVenda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemVenda itemVenda = db.ItensVenda.Find(id);
            if (itemVenda == null)
            {
                return HttpNotFound();
            }
            return View(itemVenda);
        }
        public ActionResult Create(int idProduto)
        {

            idProduto = Convert.ToInt32(Request.QueryString["idProduto"]);
            ItemVendaDAO.AdicionarItemVenda(idProduto);
            ViewBag.ProdutoId = new SelectList(db.Produtos, "ProdutoId", "ProdutoNome");
            return RedirectToAction("Index");
        }


        // POST: ItemVenda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemVendaId,ProdutoId,ItemVendaPreco,ItemVendaQuantidade,IdCarrinho,DataDaAdicao")] ItemVenda itemVenda)
        {
            if (ModelState.IsValid)
            {
                db.ItensVenda.Add(itemVenda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProdutoId = new SelectList(db.Produtos, "ProdutoId", "ProdutoNome", itemVenda.ProdutoId);
            return View(itemVenda);
        }

        // GET: ItemVenda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemVenda itemVenda = db.ItensVenda.Find(id);
            if (itemVenda == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProdutoId = new SelectList(db.Produtos, "ProdutoId", "ProdutoNome", itemVenda.ProdutoId);
            return View(itemVenda);
        }

        // POST: ItemVenda/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemVendaId,ProdutoId,ItemVendaPreco,ItemVendaQuantidade,IdCarrinho,DataDaAdicao")] ItemVenda itemVenda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(itemVenda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProdutoId = new SelectList(db.Produtos, "ProdutoId", "ProdutoNome", itemVenda.ProdutoId);
            return View(itemVenda);
        }

        // GET: ItemVenda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemVenda itemVenda = db.ItensVenda.Find(id);
            if (itemVenda == null)
            {
                return HttpNotFound();
            }
            return View(itemVenda);
        }

        // POST: ItemVenda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemVenda itemVenda = db.ItensVenda.Find(id);
            db.ItensVenda.Remove(itemVenda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaGaucha/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LojaGaucha.Models;
using LojaGaucha.DAL;

namespace LojaGaucha.Controllers
{
    public class ProdutoController : Controller
    {
        private Entities db = new Entities();


        // GET: Produto
        public ActionResult HomeCliente()
        {
            var produtos = db.Produtos.Include(p => p.Categoria);
            return View(produtos.ToList());
        }
        public ActionResult Estoque()
        {
            var produtos = db.Produtos.Include(p => p.Categoria);
            return View(produtos.ToList());
        }
        // GET: Produto
        public ActionResult Index()
        {
            var produtos = db.Produtos.Include(p => p.Categoria);
            return View(produtos.ToList());
        }

        // GET: Produto/Details/5
        public ActionResult Details(int? idProduto)
        {
            if (idProduto == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(idProduto);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }
        //Session["IdPessoa"] = pessoa.PessoaId;
        // GET: Produto/Create
        public ActionResult Create()
        {
           
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome");
            return View();
        }
        // GET: Produto/Edit/5
        public ActionResult EditQuantidade(int? id)
        {
            Session["IdProduto"] = id;
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome" );
            return View();
        }

        // POST: Produto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProdutoId,ProdutoNome,ProdutoDescricao,ProdutoPreco,ProdutoQuantidade,ProdutoImagem,CategoriaId,Peso")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                //ver view

                ProdutoDAO.CadastrarProduto(produto);
                return RedirectToAction("Index");
            }

            return View(produto);
        }

        // GET: Produto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome", produto.CategoriaId);
            return View(produto);
        }


        // POST: Produto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProdutoId,ProdutoNome,ProdutoDescricao,ProdutoPreco,ProdutoQuantidade,ProdutoImagem,CategoriaId,Peso")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome", produto.CategoriaId);
            return View(produto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditQuantidade([Bind(Include = "ProdutoId,ProdutoQuantidade")] Produto produto)
        {
            produto.ProdutoId = Convert.ToInt32(Session["IdProduto"]);
            ProdutoDAO.AumentarQuantidadeDeProdutoAoAdicionaloAoCarrinho(produto.ProdutoId, produto.ProdutoQuantidade);
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome", produto.CategoriaId);
            return View();
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produto produto = db.Produtos.Find(id);
            db.Produtos.Remove(produto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaGaucha/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LojaGaucha.Models;
using LojaGaucha.DAL;

namespace LojaGaucha.Controllers
{
    public class VendaController : Controller
    {
        private Entities db = new Entities();

        // GET: Venda
        public ActionResult Index()
        {
            return View(db.Vendas.ToList());
        }

        // GET: Venda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venda venda = db.Vendas.Find(id);
            if (venda == null)
            {
                return HttpNotFound();
            }
            return View(venda);
        }

        // GET: Venda/Create

        public ActionResult Create()
        {
            
            Pessoa pessoa = new Pessoa();
            Venda venda = new Venda();
            var idPessoa = int.Parse(Session["IdPessoa"].ToString());
            venda.ClienteID = idPessoa;
            venda.CarrinhoId = ItemVendaDAO.RetornarCarrinhoId();
            venda.Itens = ItemVendaDAO.RetornarItensDoCarrinho();
            VendaDAO.CadastrarVenda(venda);
            ItemVendaDAO.ZerarCarrinho();
            ViewBag.ProdutoId = new SelectList(db.Produtos, "ProdutoId", "ProdutoNome");
            return View("Index");
        }

        //public void asas()
        //{
        //    Session["Guid"] = new Guid;
        //    var carrinho = retrieve.where(x => x.guid == guid);
        //    Se
        //}

        // POST: Venda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VendaId,CarrinhoId")] Venda venda)
        {
            if (ModelState.IsValid)
            {
                db.Vendas.Add(venda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(venda);
        }

        // GET: Venda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venda venda = db.Vendas.Find(id);
            if (venda == null)
            {
                return HttpNotFound();
            }
            return View(venda);
        }

        // POST: Venda/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VendaId,CarrinhoId")] Venda venda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(venda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(venda);
        }

        // GET: Venda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venda venda = db.Vendas.Find(id);
            if (venda == null)
            {
                return HttpNotFound();
            }
            return View(venda);
        }

        // POST: Venda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Venda venda = db.Vendas.Find(id);
            db.Vendas.Remove(venda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaGaucha/Views/ItemVenda/Comprar.cshtml
fgreg

LojaGaucha/Views/ItemVenda/Create.cshtml
@model LojaGaucha.Models.ItemVenda

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ItemVenda</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoId, "ProdutoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProdutoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProdutoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemVendaPreco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemVendaPreco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemVendaPreco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemVendaQuantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemVendaQuantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemVendaQuantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCarrinho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdCarrinho, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdCarrinho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDaAdicao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDaAdicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDaAdicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LojaGaucha/Views/ItemVenda/Delete.cshtml
@model LojaGaucha.Models.ItemVenda

@{
    ViewBag.Title = "Delete";
}

<h2>Remover</h2>

<h3>Tem certeza que deseja remover este Produto?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemVendaProduto.ProdutoNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemVendaProduto.ProdutoNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemVendaPreco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemVendaPreco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemVendaQuantidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemVendaQuantidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDaAdicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDaAdicao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover do Carrinho" class="btn btn-warning" /> &nbsp; &nbsp;| &nbsp; &nbsp;
            @Html.ActionLink("Voltar ao Carrinho", "Index", "", new {@class="btn btn-info"})
        </div>
    }
</div>

LojaGaucha/Views/ItemVenda/Details.cshtml
@model LojaGaucha.Models.ItemVenda

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ItemVenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemVendaProduto.ProdutoNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemVendaProduto.ProdutoNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemVendaPreco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemVendaPreco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemVendaQuantidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemVendaQuantidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdCarrinho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCarrinho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDaAdicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDaAdicao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ItemVendaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LojaGaucha/Views/ItemVenda/Edit.cshtml
@model LojaGaucha.Models.ItemVenda

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ItemVenda</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemVendaId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoId, "ProdutoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProdutoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProdutoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemVendaPreco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemVendaPreco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemVendaPreco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemVendaQuantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemVendaQuantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemVendaQuantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCarrinho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdCarrinho, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdCarrinho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDaAdicao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDaAdicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDaAdicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LojaGaucha/Views/ItemVenda/Index.cshtml
@model IEnumerable<LojaGaucha.Models.ItemVenda>

@{
    ViewBag.Title = "Index";
}
<div class=nav navbar-collapse collapse">
    <h2>Carrinho de Compras</h2>
</div>

@*<div class="nav navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li> @Html.ActionLink("Continuar Comprando", "HomeCliente", "Produto")</li>
        </ul>
    </div>*@
<table class="table table-striped table-hover ">
    <tr>
        <th>
            Nome
        </th>
        <th>
            Valor Unitario
        </th>
        <th>
            Quantidade
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ItemVendaProduto.ProdutoNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemVendaPreco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemVendaQuantidade)
            </td>
            <td>
                @Html.ActionLink("Detalhe do Produto", "ProdutoDetails", new { id = item.ItemVendaId }, new { @class = "btn btn-info" }) &nbsp; &nbsp;| &nbsp; &nbsp;
                @Html.ActionLink("Remover Produto", "Delete", new { id = item.ItemVendaId }, new { @class = "btn btn-warning" })
            </td>
        </tr>

    }
</table>

@Html.ActionLink("Finalizar Compra", "Create", "Venda", null, new { @class = "btn btn-success" })&nbsp; &nbsp; &nbsp;| &nbsp; &nbsp;
@Html.ActionLink("Continuar Comprando", "HomeCliente", "Produto", null, new { @class = "btn btn-info" })

LojaGaucha/Views/ItemVenda/ProdutoDetails.cshtml
@model LojaGaucha.Models.ItemVenda

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProdutoNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdutoDescricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoDescricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdutoPreco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoPreco)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProdutoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>