LojaGaucha/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LojaGaucha.Models
{
    [Table("Produtos")]
    public class Produto
    {
        [Key]
        public int ProdutoId { get; set; }
        [Required]
        [StringLength(100)]
        public string ProdutoNome { get; set; }
        [Required]
        [StringLength(1000)]
        public string ProdutoDescricao { get; set; }
        public double ProdutoPreco { get; set; }
        public int ProdutoQuantidade { get; set; }
        public string ProdutoImagem { get; set; }
        public virtual Categoria Categoria { get; set; }
        public int CategoriaId { get; set; }
        public string Peso { get; set; }
    }
}

LojaGaucha/Controllers/ItemVendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LojaGaucha.Models;
using LojaGaucha.DAL;

namespace LojaGaucha.Controllers
{
    public class ItemVendaController : Controller
    {
        private Entities db = new Entities();

        // GET: ItemVenda
        public ActionResult Index()
        {
            var itensVenda = db.ItensVenda.Include(i => i.ItemVendaProduto);
            return View(itensVenda.ToList());
        }
        // GET: ItemVenda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemVenda itemVenda = db.ItensVenda.Find(id);
            if (itemVenda == null)
            {
                return HttpNotFound();
            }
            return View(itemVenda);
        }
        public ActionResult Create(int idProduto)
        {

            idProduto = Convert.ToInt32(Request.QueryString["idProduto"]);
            ItemVendaDAO.AdicionarItemVenda(idProduto);
            ViewBag.ProdutoId = new SelectList(db.Produtos, "ProdutoId", "ProdutoNome");
            return RedirectToAction("Index");
        }


        // POST: ItemVenda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemVendaId,ProdutoId,ItemVendaPreco,ItemVendaQuantidade,IdCarrinho,DataDaAdicao")] ItemVenda itemVenda)
        {
            if (ModelState.IsValid)
            {
                db.ItensVenda.Add(itemVenda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProdutoId = new SelectList(db.Produtos, "ProdutoId", "ProdutoNome", itemVenda.ProdutoId);
            return View(itemVenda);
        }

        // GET: ItemVenda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemVenda itemVenda = db.ItensVenda.Find(id);
            if (itemVenda == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProdutoId = new SelectList(db.Produtos, "ProdutoId", "ProdutoNome", itemVenda.ProdutoId);
            return View(itemVenda);
        }

        // POST: ItemVenda/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemVendaId,ProdutoId,ItemVendaPreco,ItemVendaQuantidade,IdCarrinho,DataDaAdicao")] ItemVenda itemVenda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(itemVenda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProdutoId = new SelectList(db.Produtos, "ProdutoId", "ProdutoNome", itemVenda.ProdutoId);
            return View(itemVenda);
        }

        // GET: ItemVenda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemVenda itemVenda = db.ItensVenda.Find(id);
            if (itemVenda == null)
            {
                return HttpNotFound();
            }
            return View(itemVenda);
        }

        // POST: ItemVenda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemVenda itemVenda = db.ItensVenda.Find(id);
            db.ItensVenda.Remove(itemVenda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaGaucha/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LojaGaucha.Models;
using LojaGaucha.DAL;

namespace LojaGaucha.Controllers
{
    public class ProdutoController : Controller
    {
        private Entities db = new Entities();


        // GET: Produto
        public ActionResult HomeCliente()
        {
            var produtos = db.Produtos.Include(p => p.Categoria);
            return View(produtos.ToList());
        }
        public ActionResult Estoque()
        {
            var produtos = db.Produtos.Include(p => p.Categoria);
            return View(produtos.ToList());
        }
        // GET: Produto
        public ActionResult Index()
        {
            var produtos = db.Produtos.Include(p => p.Categoria);
            return View(produtos.ToList());
        }

        // GET: Produto/Details/5
        public ActionResult Details(int? idProduto)
        {
            if (idProduto == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(idProduto);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }
        //Session["IdPessoa"] = pessoa.PessoaId;
        // GET: Produto/Create
        public ActionResult Create()
        {
           
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome");
            return View();
        }
        // GET: Produto/Edit/5
        public ActionResult EditQuantidade(int? id)
        {
            Session["IdProduto"] = id;
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome" );
            return View();
        }

        // POST: Produto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProdutoId,ProdutoNome,ProdutoDescricao,ProdutoPreco,ProdutoQuantidade,ProdutoImagem,CategoriaId,Peso")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                //ver view

                ProdutoDAO.CadastrarProduto(produto);
                return RedirectToAction("Index");
            }

            return View(produto);
        }

        // GET: Produto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome", produto.CategoriaId);
            return View(produto);
        }


        // POST: Produto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProdutoId,ProdutoNome,ProdutoDescricao,ProdutoPreco,ProdutoQuantidade,ProdutoImagem,CategoriaId,Peso")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome", produto.CategoriaId);
            return View(produto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditQuantidade([Bind(Include = "ProdutoId,ProdutoQuantidade")] Produto produto)
        {
            produto.ProdutoId = Convert.ToInt32(Session["IdProduto"]);
            ProdutoDAO.AumentarQuantidadeDeProdutoAoAdicionaloAoCarrinho(produto.ProdutoId, produto.ProdutoQuantidade);
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome", produto.CategoriaId);
            return View();
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produto produto = db.Produtos.Find(id);
            db.Produtos.Remove(produto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaGaucha/Views/Produto/CarrinhoDeCompras.cshtml
@model LojaGaucha.Models.Produto
@{
    ViewBag.Title = "Carrinho De compras";
    Layout = "~/Views/Shared/Template.cshtml";
}
<h1>Carrinho De Compras</h1>

LojaGaucha/Views/Produto/Create.cshtml
@model LojaGaucha.Models.Produto

@{
    ViewBag.Title = "Create";
}
<p>
    <h2>Cadastrar Produto</h2>
</p>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoNome, "Produto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoDescricao,"Descrição", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoDescricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoDescricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoPreco,"Preço", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoPreco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoPreco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoQuantidade,"Quantidade em Estoque", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoQuantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoQuantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoImagem, "Imagem", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoImagem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoImagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, "Peso", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" /> &nbsp; &nbsp;| &nbsp; &nbsp;
                @Html.ActionLink("Voltar a tela inicial", "Index", "", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

LojaGaucha/Views/Produto/Delete.cshtml
@model LojaGaucha.Models.Produto

@{
    ViewBag.Title = "Delete";
}

<h2>Remover Produto</h2>

<h3>Deseja mesmo remover este produto?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categoria.CategoriaNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.CategoriaNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdutoNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdutoDescricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoDescricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdutoPreco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoPreco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdutoQuantidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoQuantidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdutoImagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoImagem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-default" />&nbsp; &nbsp;| &nbsp; &nbsp;
            @Html.ActionLink("Voltar a tela inicial", "Index", "", new {@class = "btn btn-default" })
        </div>
    }
</div>

LojaGaucha/Views/Produto/Details.cshtml
@model LojaGaucha.Models.Produto

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProdutoNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdutoDescricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoDescricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdutoPreco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoPreco)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

    </dl>
    <hr />
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ProdutoId }, new { @class = "btn btn-default" })&nbsp; &nbsp;| &nbsp; &nbsp;
    @Html.ActionLink("Voltar ao Menu", "Index", "", new { @class = "btn btn-default"})
</p>

LojaGaucha/Views/Produto/Edit.cshtml
@model LojaGaucha.Models.Produto

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProdutoId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoNome, "Produto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoDescricao, "Descrição", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoDescricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoDescricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoPreco, "Preço", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoPreco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoPreco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoQuantidade, "Quantidade", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoQuantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoQuantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoImagem, "Imagem", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoImagem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoImagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, "Peso", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />&nbsp; &nbsp;| &nbsp; &nbsp;
                @Html.ActionLink("Voltar ao Menu", "Index", "", new { @class = "btn btn-deafult" })
            </div>
        </div>
    </div>
}

<div>

</div>

LojaGaucha/Views/Produto/EditQuantidade.cshtml
@model LojaGaucha.Models.Produto

@{
    ViewBag.Title = "EditQuantidade";
}

<h2>Adicionar Quantidade</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoQuantidade, "Quantidade", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdutoQuantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdutoQuantidade, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Alterar" class="btn btn-default" />&nbsp; &nbsp;| &nbsp; &nbsp;
                @Html.ActionLink("Voltar", "Estoque", "", new {@class = "btn btn-default" })
            </div>
        </div>
    </div>
}

LojaGaucha/Views/Produto/Estoque.cshtml
@model IEnumerable<LojaGaucha.Models.Produto>
@{
    ViewBag.Title = "Estoque";
}

<h2>Estoque</h2>

<table class="table table-striped table-hover ">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.CategoriaNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdutoNome)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.ProdutoQuantidade)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.CategoriaNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProdutoNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProdutoQuantidade)
            </td>
            <td>
             
                @Html.ActionLink("Editar", "Edit", new { id = item.ProdutoId }, new { @class = "btn btn-info"} )&nbsp; &nbsp;| &nbsp; &nbsp;
                @Html.ActionLink("Detalhe", "Details", "Produto", new { id = item.ProdutoId }, new { @class = "btn btn-info" })&nbsp; &nbsp;| &nbsp; &nbsp;
                @Html.ActionLink("Adicionar Quantidade", "EditQuantidade", new { id = item.ProdutoId }, new { @class = "btn btn-info" })&nbsp; &nbsp;| &nbsp; &nbsp;
                @Html.ActionLink("Remover", "Delete", new { id = item.ProdutoId }, new { @class = "btn btn-warning" })
                
            </td>
        </tr>
    }

</table>

LojaGaucha/Views/Produto/HomeCliente.cshtml
@model IEnumerable<LojaGaucha.Models.Produto>


<h1>Perifericos</h1>
@foreach (var item in Model)
{

    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">
                @Html.DisplayFor(modelItem => item.ProdutoNome)
            </h3>
        </div>
        <div class="panel-body">
           
                <h4>Preço</h4>
                @Html.DisplayFor(modelItem => item.ProdutoPreco)
                
                <h4>Peso</h4>
                @Html.DisplayFor(modelItem => item.Peso)

           
        </div>
        <div>
            @Html.ActionLink("Detalhe do Produto", "Details", new { idProduto = item.ProdutoId }, new { @class = "btn btn-info" }) &nbsp; &nbsp; - &nbsp; &nbsp;
            @Html.ActionLink("Adicionar Ao Carrinho", "Create", "ItemVenda", new { idProduto = item.ProdutoId }, new { @class = "btn btn-success" })
        </div>
 
    </div>

}

     

LojaGaucha/Views/Produto/Index.cshtml
@model IEnumerable<LojaGaucha.Models.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Produtos Cadastrados</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.CategoriaNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdutoNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdutoDescricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdutoPreco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdutoQuantidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdutoImagem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Peso)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria.CategoriaNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdutoNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdutoDescricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdutoPreco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdutoQuantidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdutoImagem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Peso)
        </td>
        <td>
            <p>
                @Html.ActionLink("Editar", "Edit", new { id = item.ProdutoId }, new { @class = "btn btn-info" })
            </p>
            <p>
                @Html.ActionLink("Detalhes", "Details", "Produto", new { idProduto = item.ProdutoId }, new { @class = "btn btn-info" })
            </p>
            <p>
                @Html.ActionLink("Remover", "Delete", new { id = item.ProdutoId }, new { @class = "btn btn-warning" })
            </p>
        </td>
    </tr>


}

</table>

<p>
    @Html.ActionLink("Cadastrar Produto", "Create", "", new { @class = "btn btn-default" })
</p>