LojaGaucha/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LojaGaucha.Models
{
    [Table("Pessoas")]
    public class Pessoa
    {
        [Key]
        public int PessoaId { get; set; }
        [Required]
        public string PessoaNome { get; set; }
        [Required]
        [EmailAddress]
        public string PessoaEmail { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string ClienteSenha { get; set; }
        [Required]
        public string ClienteCPF { get; set; }
        [Required]
        public string ClienteTelefone { get; set; }
        //parametro ("PessoaNivel") mostra a diferenca entre o cliente e funcionario
        //se o valo for 1 ele é funcionario; se o valor for 2 ele é o cliente
        //adicionar manualmente alguns funcionarios, na hora de cadastrar o cliente
        //fazer esse parametro receber 2-> (PessoaNivel = 2;)
        public int PessoaNivel { get; set; }
        [Display(Name = "Confirmação de Senha")]
        [Compare("ClienteSenha", ErrorMessage = "Os campos não coincidem")]
        [DataType(DataType.Password)]
        [NotMapped]
        public string ConfimacaoSenha { get; set; }
    }
}

LojaGaucha/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LojaGaucha.Models;
using LojaGaucha.DAL;

namespace LojaGaucha.Controllers
{
    public class CategoriaController : Controller
    {
        private Entities db = new Entities();

        // GET: Categoria
        public ActionResult Index()
        {
            return View(db.Categorias.ToList());
        }

        // GET: Categoria/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // GET: Categoria/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categoria/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoriaId,CategoriaNome")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                CategoriaDAO.CadastrarCategoria(categoria);
                return RedirectToAction("Index");
            }

            return View(categoria);
        }
    // GET: Categoria/Edit/5
    public ActionResult Edit(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        Categoria categoria = db.Categorias.Find(id);
        if (categoria == null)
        {
            return HttpNotFound();
        }
        return View(categoria);
    }

    // POST: Categoria/Edit/5
    // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
    // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "CategoriaId,CategoriaNome")] Categoria categoria)
    {
        if (ModelState.IsValid)
        {
            db.Entry(categoria).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(categoria);
    }

    // GET: Categoria/Delete/5
    public ActionResult Delete(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        Categoria categoria = db.Categorias.Find(id);
        if (categoria == null)
        {
            return HttpNotFound();
        }
        return View(categoria);
    }

    // POST: Categoria/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
        Categoria categoria = db.Categorias.Find(id);
        db.Categorias.Remove(categoria);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            db.Dispose();
        }
        base.Dispose(disposing);
    }
}
}

LojaGaucha/Controllers/PessoaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LojaGaucha.Models;
using LojaGaucha.DAL;
using System.Web.Security;

namespace LojaGaucha.Controllers
{
    public class PessoaController : Controller
    {
        private Entities db = new Entities();

        // GET: Pessoa
        public ActionResult Index()
        {
            return View(db.Pessoas.ToList());
        }


        // GET: Pessoa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoa = db.Pessoas.Find(id);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }

        // GET: Pessoa/Create
        public ActionResult Create()
        {
            return View();
        }
      public ActionResult HomeFuncionario()
        {
            return View();
        }

        // POST: Pessoa/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PessoaId,PessoaNome,PessoaEmail,ClienteSenha,ClienteCPF,ClienteTelefone,PessoaNivel,ConfimacaoSenha")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                pessoa.PessoaNivel = 1;
                PessoaDAO.CadastrarPessoa(pessoa);
                return RedirectToAction("Login");
            }

            return View(pessoa);
        }



        public ActionResult Login()
        {



            return View();
        }

        [HttpPost]
        public ActionResult Login([Bind(Include = "PessoaEmail, ClienteSenha")]Pessoa pessoa)
        {
            if (PessoaDAO.BuscarPessoaPorEmailSenha(pessoa) != null)
            {
                pessoa = PessoaDAO.BuscarPessoaPorEmailSenha(pessoa);
                if (pessoa.PessoaNivel == 1)
                {
                    //Cria uma sessao onde fica salvo o IdDaPessoa
                    Session["IdPessoa"] = pessoa.PessoaId;
                    FormsAuthentication.SetAuthCookie(pessoa.PessoaEmail, false);
                    return RedirectToAction("HomeCliente", "Produto");
                }else
                {
                    Session["IdPessoa"] = pessoa.PessoaId;
                    FormsAuthentication.SetAuthCookie(pessoa.PessoaEmail, false);
                    return RedirectToAction("HomeFuncionario", "Pessoa");
                }
            }
            else
            {
                ModelState.AddModelError("", "E-mail ou senha não coincidem");
                return View();
            }
        }

        public ActionResult Logout()
        {
            Session.RemoveAll();

           // var idPessoa = int.Parse(Session["IdPessoa"].ToString());


            return View();
        }





        // GET: Pessoa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoa = db.Pessoas.Find(id);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }

        // POST: Pessoa/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PessoaId,PessoaNome,PessoaEmail,ClienteSenha,ClienteCPF,ClienteTelefone,PessoaNivel,ConfimacaoSenha")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pessoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pessoa);
        }

        // GET: Pessoa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoa = db.Pessoas.Find(id);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }

        // POST: Pessoa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pessoa pessoa = db.Pessoas.Find(id);
            db.Pessoas.Remove(pessoa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaGaucha/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LojaGaucha.Models;
using LojaGaucha.DAL;

namespace LojaGaucha.Controllers
{
    public class ProdutoController : Controller
    {
        private Entities db = new Entities();


        // GET: Produto
        public ActionResult HomeCliente()
        {
            var produtos = db.Produtos.Include(p => p.Categoria);
            return View(produtos.ToList());
        }
        public ActionResult Estoque()
        {
            var produtos = db.Produtos.Include(p => p.Categoria);
            return View(produtos.ToList());
        }
        // GET: Produto
        public ActionResult Index()
        {
            var produtos = db.Produtos.Include(p => p.Categoria);
            return View(produtos.ToList());
        }

        // GET: Produto/Details/5
        public ActionResult Details(int? idProduto)
        {
            if (idProduto == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(idProduto);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }
        //Session["IdPessoa"] = pessoa.PessoaId;
        // GET: Produto/Create
        public ActionResult Create()
        {
           
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome");
            return View();
        }
        // GET: Produto/Edit/5
        public ActionResult EditQuantidade(int? id)
        {
            Session["IdProduto"] = id;
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome" );
            return View();
        }

        // POST: Produto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProdutoId,ProdutoNome,ProdutoDescricao,ProdutoPreco,ProdutoQuantidade,ProdutoImagem,CategoriaId,Peso")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                //ver view

                ProdutoDAO.CadastrarProduto(produto);
                return RedirectToAction("Index");
            }

            return View(produto);
        }

        // GET: Produto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome", produto.CategoriaId);
            return View(produto);
        }


        // POST: Produto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProdutoId,ProdutoNome,ProdutoDescricao,ProdutoPreco,ProdutoQuantidade,ProdutoImagem,CategoriaId,Peso")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome", produto.CategoriaId);
            return View(produto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditQuantidade([Bind(Include = "ProdutoId,ProdutoQuantidade")] Produto produto)
        {
            produto.ProdutoId = Convert.ToInt32(Session["IdProduto"]);
            ProdutoDAO.AumentarQuantidadeDeProdutoAoAdicionaloAoCarrinho(produto.ProdutoId, produto.ProdutoQuantidade);
            ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoriaId", "CategoriaNome", produto.CategoriaId);
            return View();
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produto produto = db.Produtos.Find(id);
            db.Produtos.Remove(produto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaGaucha/Views/Pessoa/Create.cshtml
@model LojaGaucha.Models.Pessoa

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Template.cshtml";
}
<p class="text-muted">
    <h2>Cadastrar</h2>
</p>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
   
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PessoaNome,"Nome", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PessoaEmail,"Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteSenha,"Senha", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClienteSenha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClienteSenha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfimacaoSenha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfimacaoSenha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfimacaoSenha, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ClienteCPF,"CPF", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClienteCPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClienteCPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteTelefone,"Telefone", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClienteTelefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClienteTelefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PessoaNivel,"Nivel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaNivel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaNivel, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>

LojaGaucha/Views/Pessoa/Delete.cshtml
@model LojaGaucha.Models.Pessoa

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Template.cshtml";
}
<p>
    <h2>Remover cadastro</h2>
</p>        

<h3>Deseja mesmo remover este cadastro?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PessoaNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PessoaEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClienteSenha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClienteSenha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClienteCPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClienteCPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClienteTelefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClienteTelefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PessoaNivel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaNivel)
        </dd>

    </dl>
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-default" />&nbsp; &nbsp; | &nbsp; &nbsp;
            @Html.ActionLink("Voltar ao Menu", "Index","", new {@class = "btn btn-default" })
        </div>
    }
</div>

LojaGaucha/Views/Pessoa/Details.cshtml
@model LojaGaucha.Models.Pessoa

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Template.cshtml";
}

<h2>Detalhes</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PessoaNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PessoaEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClienteSenha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClienteSenha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClienteCPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClienteCPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClienteTelefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClienteTelefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PessoaNivel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PessoaNivel)
        </dd>

    </dl>
    <hr />
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.PessoaId }, new { @class = "btn btn-default" })&nbsp; &nbsp; | &nbsp; &nbsp;
    @Html.ActionLink("Voltar ao Menu", "Index","", new { @class = "btn btn-default"})
</p>

LojaGaucha/Views/Pessoa/Edit.cshtml
@model LojaGaucha.Models.Pessoa

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Template.cshtml";
}

<h2>Editar Cadastro</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PessoaId)

        <div class="form-group">
            @Html.LabelFor(model => model.PessoaNome, "Nome",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PessoaEmail, "E-mail",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteSenha, "Senha",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClienteSenha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClienteSenha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteCPF, "CPF", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClienteCPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClienteCPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteTelefone, "Telefone", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClienteTelefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClienteTelefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PessoaNivel, "Nivel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PessoaNivel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PessoaNivel, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />&nbsp; &nbsp; | &nbsp; &nbsp;
                @Html.ActionLink("Voltar ao Menu", "Index", "", new { @class = "btn btn-default"})
            </div>
        </div>
    </div>
}

<div>

</div>

LojaGaucha/Views/Pessoa/HomeFuncionario.cshtml
@model LojaGaucha.Models.Pessoa

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/Template.cshtml";
}
<h2>Area dos Funcionarios</h2>
<hr />
<p>
    <li>@Html.ActionLink("Cadastrar Produto", "Create", "Produto")</li>
</p>
<p>
    <li>@Html.ActionLink("Cadastrar Categoria", "Create", "Categoria")</li>
</p>
<p>
    <li>@Html.ActionLink("Verificar Estoque", "Estoque", "Produto")</li>
</p>
<p>
    <li>@Html.ActionLink("Gerenciar Usuarios", "Index", "Pessoa")</li>
</p>

LojaGaucha/Views/Pessoa/Index.cshtml
@model IEnumerable<LojaGaucha.Models.Pessoa>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Template.cshtml";
}

<h2>Lista de Usuarios</h2>

<table class="table table-striped table-hover ">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PessoaNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PessoaEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClienteSenha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClienteCPF)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClienteTelefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PessoaNivel)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PessoaNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PessoaEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClienteSenha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClienteCPF)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClienteTelefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PessoaNivel)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.PessoaId }, new { @class = "btn btn-info" })&nbsp; &nbsp; &nbsp;| &nbsp; &nbsp;
            @Html.ActionLink("Detalhes", "Details", new { id = item.PessoaId }, new { @class = "btn btn-info" })&nbsp; &nbsp; &nbsp;| &nbsp; &nbsp;
            @Html.ActionLink("Remover", "Delete", new { id=item.PessoaId }, new { @class = "btn btn-warning" })
        </td>
    </tr>
}

</table>